/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON_DASH = 1,
  anon_sym_DOT = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  sym_unquoted_atom = 6,
  aux_sym_quoted_atom_token1 = 7,
  sym_format_string_placeholder = 8,
  sym_single_quoted_character_escape = 9,
  sym_single_quoted_content = 10,
  aux_sym_double_quoted_string_token1 = 11,
  sym_double_quoted_character_escape = 12,
  sym_double_quoted_content = 13,
  aux_sym_backtick_string_token1 = 14,
  sym_backticked_character_escape = 15,
  sym_backticked_content = 16,
  sym_variable = 17,
  sym_source_file = 18,
  sym_directive = 19,
  sym_clause = 20,
  sym__term = 21,
  sym__restricted_operators_term = 22,
  sym_compound_term = 23,
  sym_atom = 24,
  sym_quoted_atom = 25,
  sym__single_quoted_inner = 26,
  sym_string = 27,
  sym_double_quoted_string = 28,
  sym__double_quoted_string_inner = 29,
  sym_backtick_string = 30,
  sym__backtick_string_inner = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_compound_term_repeat1 = 33,
  aux_sym_quoted_atom_repeat1 = 34,
  aux_sym_double_quoted_string_repeat1 = 35,
  aux_sym_backtick_string_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_DASH] = ":-",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_unquoted_atom] = "unquoted_atom",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [sym_format_string_placeholder] = "format_string_placeholder",
  [sym_single_quoted_character_escape] = "single_quoted_character_escape",
  [sym_single_quoted_content] = "single_quoted_content",
  [aux_sym_double_quoted_string_token1] = "double_quoted_string_token1",
  [sym_double_quoted_character_escape] = "double_quoted_character_escape",
  [sym_double_quoted_content] = "double_quoted_content",
  [aux_sym_backtick_string_token1] = "backtick_string_token1",
  [sym_backticked_character_escape] = "backticked_character_escape",
  [sym_backticked_content] = "backticked_content",
  [sym_variable] = "variable",
  [sym_source_file] = "source_file",
  [sym_directive] = "directive",
  [sym_clause] = "clause",
  [sym__term] = "_term",
  [sym__restricted_operators_term] = "_restricted_operators_term",
  [sym_compound_term] = "compound_term",
  [sym_atom] = "atom",
  [sym_quoted_atom] = "quoted_atom",
  [sym__single_quoted_inner] = "_single_quoted_inner",
  [sym_string] = "string",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym__double_quoted_string_inner] = "_double_quoted_string_inner",
  [sym_backtick_string] = "backtick_string",
  [sym__backtick_string_inner] = "_backtick_string_inner",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_compound_term_repeat1] = "compound_term_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [aux_sym_double_quoted_string_repeat1] = "double_quoted_string_repeat1",
  [aux_sym_backtick_string_repeat1] = "backtick_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_unquoted_atom] = sym_unquoted_atom,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [sym_format_string_placeholder] = sym_format_string_placeholder,
  [sym_single_quoted_character_escape] = sym_single_quoted_character_escape,
  [sym_single_quoted_content] = sym_single_quoted_content,
  [aux_sym_double_quoted_string_token1] = aux_sym_double_quoted_string_token1,
  [sym_double_quoted_character_escape] = sym_double_quoted_character_escape,
  [sym_double_quoted_content] = sym_double_quoted_content,
  [aux_sym_backtick_string_token1] = aux_sym_backtick_string_token1,
  [sym_backticked_character_escape] = sym_backticked_character_escape,
  [sym_backticked_content] = sym_backticked_content,
  [sym_variable] = sym_variable,
  [sym_source_file] = sym_source_file,
  [sym_directive] = sym_directive,
  [sym_clause] = sym_clause,
  [sym__term] = sym__term,
  [sym__restricted_operators_term] = sym__restricted_operators_term,
  [sym_compound_term] = sym_compound_term,
  [sym_atom] = sym_atom,
  [sym_quoted_atom] = sym_quoted_atom,
  [sym__single_quoted_inner] = sym__single_quoted_inner,
  [sym_string] = sym_string,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym__double_quoted_string_inner] = sym__double_quoted_string_inner,
  [sym_backtick_string] = sym_backtick_string,
  [sym__backtick_string_inner] = sym__backtick_string_inner,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_compound_term_repeat1] = aux_sym_compound_term_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [aux_sym_double_quoted_string_repeat1] = aux_sym_double_quoted_string_repeat1,
  [aux_sym_backtick_string_repeat1] = aux_sym_backtick_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_unquoted_atom] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_format_string_placeholder] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_double_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_double_quoted_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_backtick_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_backticked_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_backticked_content] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym__restricted_operators_term] = {
    .visible = false,
    .named = true,
  },
  [sym_compound_term] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quoted_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym__double_quoted_string_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_backtick_string] = {
    .visible = true,
    .named = true,
  },
  [sym__backtick_string_inner] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_backtick_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_functor = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_functor] = "functor",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_functor, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 22,
        '\'', 17,
        '(', 13,
        ')', 15,
        ',', 14,
        '.', 12,
        ':', 4,
        '\\', 2,
        '`', 26,
        '~', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 23,
        '\'', 19,
        '`', 27,
        '\\', 19,
        'n', 19,
        'r', 19,
        't', 19,
        'v', 19,
      );
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == '`') ADVANCE(26);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == 'n' ||
          lookahead == 't' ||
          lookahead == '~') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == '\\' ||
          lookahead == '`' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(27);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_unquoted_atom);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_format_string_placeholder);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_single_quoted_character_escape);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_double_quoted_string_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_double_quoted_character_escape);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_backtick_string_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_backticked_character_escape);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_backticked_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_backticked_content);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_unquoted_atom] = ACTIONS(1),
    [aux_sym_quoted_atom_token1] = ACTIONS(1),
    [sym_format_string_placeholder] = ACTIONS(1),
    [sym_single_quoted_character_escape] = ACTIONS(1),
    [aux_sym_double_quoted_string_token1] = ACTIONS(1),
    [sym_double_quoted_character_escape] = ACTIONS(1),
    [aux_sym_backtick_string_token1] = ACTIONS(1),
    [sym_backticked_character_escape] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(36),
    [sym_directive] = STATE(2),
    [sym_clause] = STATE(2),
    [sym__term] = STATE(34),
    [sym__restricted_operators_term] = STATE(34),
    [sym_compound_term] = STATE(34),
    [sym_atom] = STATE(20),
    [sym_quoted_atom] = STATE(23),
    [sym_string] = STATE(34),
    [sym_double_quoted_string] = STATE(29),
    [sym_backtick_string] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_COLON_DASH] = ACTIONS(5),
    [sym_unquoted_atom] = ACTIONS(7),
    [aux_sym_quoted_atom_token1] = ACTIONS(9),
    [aux_sym_double_quoted_string_token1] = ACTIONS(11),
    [aux_sym_backtick_string_token1] = ACTIONS(13),
    [sym_variable] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_COLON_DASH,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(15), 1,
      sym_variable,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_atom,
    STATE(23), 1,
      sym_quoted_atom,
    STATE(29), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(3), 3,
      sym_directive,
      sym_clause,
      aux_sym_source_file_repeat1,
    STATE(34), 4,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
  [43] = 12,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_COLON_DASH,
    ACTIONS(24), 1,
      sym_unquoted_atom,
    ACTIONS(27), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(30), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(33), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(36), 1,
      sym_variable,
    STATE(20), 1,
      sym_atom,
    STATE(23), 1,
      sym_quoted_atom,
    STATE(29), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(3), 3,
      sym_directive,
      sym_clause,
      aux_sym_source_file_repeat1,
    STATE(34), 4,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
  [86] = 9,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(39), 1,
      sym_variable,
    STATE(20), 1,
      sym_atom,
    STATE(23), 1,
      sym_quoted_atom,
    STATE(29), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(38), 4,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
  [118] = 9,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(41), 1,
      sym_variable,
    STATE(20), 1,
      sym_atom,
    STATE(23), 1,
      sym_quoted_atom,
    STATE(29), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(37), 4,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
  [150] = 9,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(43), 1,
      sym_variable,
    STATE(20), 1,
      sym_atom,
    STATE(23), 1,
      sym_quoted_atom,
    STATE(29), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(32), 3,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
  [181] = 9,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(45), 1,
      sym_variable,
    STATE(20), 1,
      sym_atom,
    STATE(23), 1,
      sym_quoted_atom,
    STATE(29), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(35), 3,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
  [212] = 1,
    ACTIONS(47), 7,
      ts_builtin_sym_end,
      anon_sym_COLON_DASH,
      sym_unquoted_atom,
      aux_sym_quoted_atom_token1,
      aux_sym_double_quoted_string_token1,
      aux_sym_backtick_string_token1,
      sym_variable,
  [222] = 1,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      anon_sym_COLON_DASH,
      sym_unquoted_atom,
      aux_sym_quoted_atom_token1,
      aux_sym_double_quoted_string_token1,
      aux_sym_backtick_string_token1,
      sym_variable,
  [232] = 1,
    ACTIONS(51), 7,
      ts_builtin_sym_end,
      anon_sym_COLON_DASH,
      sym_unquoted_atom,
      aux_sym_quoted_atom_token1,
      aux_sym_double_quoted_string_token1,
      aux_sym_backtick_string_token1,
      sym_variable,
  [242] = 4,
    ACTIONS(55), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(57), 1,
      sym_double_quoted_content,
    ACTIONS(53), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(18), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [257] = 4,
    ACTIONS(59), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(63), 1,
      sym_single_quoted_content,
    ACTIONS(61), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(14), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [272] = 4,
    ACTIONS(67), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(69), 1,
      sym_backticked_content,
    ACTIONS(65), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(19), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [287] = 4,
    ACTIONS(71), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(75), 1,
      sym_single_quoted_content,
    ACTIONS(73), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(17), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [302] = 4,
    ACTIONS(79), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(81), 1,
      sym_double_quoted_content,
    ACTIONS(77), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(11), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [317] = 4,
    ACTIONS(85), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(87), 1,
      sym_backticked_content,
    ACTIONS(83), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(13), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [332] = 4,
    ACTIONS(89), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(94), 1,
      sym_single_quoted_content,
    ACTIONS(91), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(17), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [347] = 4,
    ACTIONS(100), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(102), 1,
      sym_double_quoted_content,
    ACTIONS(97), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(18), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [362] = 4,
    ACTIONS(108), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(110), 1,
      sym_backticked_content,
    ACTIONS(105), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(19), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [377] = 2,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [387] = 1,
    ACTIONS(117), 5,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [395] = 1,
    ACTIONS(119), 5,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [403] = 1,
    ACTIONS(121), 5,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [411] = 1,
    ACTIONS(123), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [418] = 1,
    ACTIONS(125), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [425] = 1,
    ACTIONS(127), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [432] = 1,
    ACTIONS(129), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [439] = 1,
    ACTIONS(131), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [446] = 1,
    ACTIONS(133), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [453] = 1,
    ACTIONS(135), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [460] = 3,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym_compound_term_repeat1,
  [470] = 3,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      aux_sym_compound_term_repeat1,
  [480] = 3,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym_compound_term_repeat1,
  [490] = 2,
    ACTIONS(148), 1,
      anon_sym_COLON_DASH,
    ACTIONS(150), 1,
      anon_sym_DOT,
  [497] = 1,
    ACTIONS(146), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [502] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
  [506] = 1,
    ACTIONS(154), 1,
      anon_sym_DOT,
  [510] = 1,
    ACTIONS(156), 1,
      anon_sym_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 118,
  [SMALL_STATE(6)] = 150,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 212,
  [SMALL_STATE(9)] = 222,
  [SMALL_STATE(10)] = 232,
  [SMALL_STATE(11)] = 242,
  [SMALL_STATE(12)] = 257,
  [SMALL_STATE(13)] = 272,
  [SMALL_STATE(14)] = 287,
  [SMALL_STATE(15)] = 302,
  [SMALL_STATE(16)] = 317,
  [SMALL_STATE(17)] = 332,
  [SMALL_STATE(18)] = 347,
  [SMALL_STATE(19)] = 362,
  [SMALL_STATE(20)] = 377,
  [SMALL_STATE(21)] = 387,
  [SMALL_STATE(22)] = 395,
  [SMALL_STATE(23)] = 403,
  [SMALL_STATE(24)] = 411,
  [SMALL_STATE(25)] = 418,
  [SMALL_STATE(26)] = 425,
  [SMALL_STATE(27)] = 432,
  [SMALL_STATE(28)] = 439,
  [SMALL_STATE(29)] = 446,
  [SMALL_STATE(30)] = 453,
  [SMALL_STATE(31)] = 460,
  [SMALL_STATE(32)] = 470,
  [SMALL_STATE(33)] = 480,
  [SMALL_STATE(34)] = 490,
  [SMALL_STATE(35)] = 497,
  [SMALL_STATE(36)] = 502,
  [SMALL_STATE(37)] = 506,
  [SMALL_STATE(38)] = 510,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__restricted_operators_term, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_string, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_string, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_term, 4, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_term, 5, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_term_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_term_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_swiprolog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "swiprolog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
