/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON_DASH = 1,
  anon_sym_DOT = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_unquoted_atom = 5,
  aux_sym_quoted_atom_token1 = 6,
  sym_format_string_placeholder = 7,
  sym_single_quoted_character_escape = 8,
  sym_single_quoted_content = 9,
  aux_sym_double_quoted_string_token1 = 10,
  sym_double_quoted_character_escape = 11,
  sym_double_quoted_content = 12,
  aux_sym_backtick_string_token1 = 13,
  sym_backticked_character_escape = 14,
  sym_backticked_content = 15,
  sym_source_file = 16,
  sym_directive = 17,
  sym_clause = 18,
  sym__term = 19,
  sym_compound_term = 20,
  sym_atom = 21,
  sym_quoted_atom = 22,
  sym__single_quoted_inner = 23,
  sym_string = 24,
  sym_double_quoted_string = 25,
  sym__double_quoted_string_inner = 26,
  sym_backtick_string = 27,
  sym__backtick_string_inner = 28,
  aux_sym_quoted_atom_repeat1 = 29,
  aux_sym_double_quoted_string_repeat1 = 30,
  aux_sym_backtick_string_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_DASH] = ":-",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_unquoted_atom] = "unquoted_atom",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [sym_format_string_placeholder] = "format_string_placeholder",
  [sym_single_quoted_character_escape] = "single_quoted_character_escape",
  [sym_single_quoted_content] = "single_quoted_content",
  [aux_sym_double_quoted_string_token1] = "double_quoted_string_token1",
  [sym_double_quoted_character_escape] = "double_quoted_character_escape",
  [sym_double_quoted_content] = "double_quoted_content",
  [aux_sym_backtick_string_token1] = "backtick_string_token1",
  [sym_backticked_character_escape] = "backticked_character_escape",
  [sym_backticked_content] = "backticked_content",
  [sym_source_file] = "source_file",
  [sym_directive] = "directive",
  [sym_clause] = "clause",
  [sym__term] = "_term",
  [sym_compound_term] = "compound_term",
  [sym_atom] = "atom",
  [sym_quoted_atom] = "quoted_atom",
  [sym__single_quoted_inner] = "_single_quoted_inner",
  [sym_string] = "string",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym__double_quoted_string_inner] = "_double_quoted_string_inner",
  [sym_backtick_string] = "backtick_string",
  [sym__backtick_string_inner] = "_backtick_string_inner",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [aux_sym_double_quoted_string_repeat1] = "double_quoted_string_repeat1",
  [aux_sym_backtick_string_repeat1] = "backtick_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_unquoted_atom] = sym_unquoted_atom,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [sym_format_string_placeholder] = sym_format_string_placeholder,
  [sym_single_quoted_character_escape] = sym_single_quoted_character_escape,
  [sym_single_quoted_content] = sym_single_quoted_content,
  [aux_sym_double_quoted_string_token1] = aux_sym_double_quoted_string_token1,
  [sym_double_quoted_character_escape] = sym_double_quoted_character_escape,
  [sym_double_quoted_content] = sym_double_quoted_content,
  [aux_sym_backtick_string_token1] = aux_sym_backtick_string_token1,
  [sym_backticked_character_escape] = sym_backticked_character_escape,
  [sym_backticked_content] = sym_backticked_content,
  [sym_source_file] = sym_source_file,
  [sym_directive] = sym_directive,
  [sym_clause] = sym_clause,
  [sym__term] = sym__term,
  [sym_compound_term] = sym_compound_term,
  [sym_atom] = sym_atom,
  [sym_quoted_atom] = sym_quoted_atom,
  [sym__single_quoted_inner] = sym__single_quoted_inner,
  [sym_string] = sym_string,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym__double_quoted_string_inner] = sym__double_quoted_string_inner,
  [sym_backtick_string] = sym_backtick_string,
  [sym__backtick_string_inner] = sym__backtick_string_inner,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [aux_sym_double_quoted_string_repeat1] = aux_sym_double_quoted_string_repeat1,
  [aux_sym_backtick_string_repeat1] = aux_sym_backtick_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_unquoted_atom] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_format_string_placeholder] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_double_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_double_quoted_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_backtick_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_backticked_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_backticked_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_compound_term] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quoted_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym__double_quoted_string_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_backtick_string] = {
    .visible = true,
    .named = true,
  },
  [sym__backtick_string_inner] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_backtick_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_functor = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_functor] = "functor",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_functor, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 21,
        '\'', 16,
        '(', 13,
        ')', 14,
        '.', 12,
        ':', 4,
        '\\', 2,
        '`', 25,
        '~', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 22,
        '\'', 18,
        '`', 26,
        '\\', 18,
        'n', 18,
        'r', 18,
        't', 18,
        'v', 18,
      );
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == '`') ADVANCE(25);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == 'n' ||
          lookahead == 't' ||
          lookahead == '~') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == '\\' ||
          lookahead == '`' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(26);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_unquoted_atom);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_format_string_placeholder);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_single_quoted_character_escape);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_double_quoted_string_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_double_quoted_character_escape);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_backtick_string_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_backticked_character_escape);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_backticked_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_backticked_content);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_unquoted_atom] = ACTIONS(1),
    [aux_sym_quoted_atom_token1] = ACTIONS(1),
    [sym_format_string_placeholder] = ACTIONS(1),
    [sym_single_quoted_character_escape] = ACTIONS(1),
    [aux_sym_double_quoted_string_token1] = ACTIONS(1),
    [sym_double_quoted_character_escape] = ACTIONS(1),
    [aux_sym_backtick_string_token1] = ACTIONS(1),
    [sym_backticked_character_escape] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym_directive] = STATE(25),
    [sym_clause] = STATE(25),
    [sym__term] = STATE(24),
    [sym_compound_term] = STATE(24),
    [sym_atom] = STATE(15),
    [sym_quoted_atom] = STATE(16),
    [sym_string] = STATE(24),
    [sym_double_quoted_string] = STATE(19),
    [sym_backtick_string] = STATE(19),
    [anon_sym_COLON_DASH] = ACTIONS(3),
    [sym_unquoted_atom] = ACTIONS(5),
    [aux_sym_quoted_atom_token1] = ACTIONS(7),
    [aux_sym_double_quoted_string_token1] = ACTIONS(9),
    [aux_sym_backtick_string_token1] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      sym_unquoted_atom,
    ACTIONS(7), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(9), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(11), 1,
      aux_sym_backtick_string_token1,
    STATE(15), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(19), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(26), 3,
      sym__term,
      sym_compound_term,
      sym_string,
  [28] = 8,
    ACTIONS(5), 1,
      sym_unquoted_atom,
    ACTIONS(7), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(9), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(11), 1,
      aux_sym_backtick_string_token1,
    STATE(15), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(19), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(30), 3,
      sym__term,
      sym_compound_term,
      sym_string,
  [56] = 8,
    ACTIONS(5), 1,
      sym_unquoted_atom,
    ACTIONS(7), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(9), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(11), 1,
      aux_sym_backtick_string_token1,
    STATE(15), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(19), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(31), 3,
      sym__term,
      sym_compound_term,
      sym_string,
  [84] = 4,
    ACTIONS(16), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(18), 1,
      sym_backticked_content,
    ACTIONS(13), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(5), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [99] = 4,
    ACTIONS(23), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(25), 1,
      sym_backticked_content,
    ACTIONS(21), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(9), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [114] = 4,
    ACTIONS(29), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(31), 1,
      sym_double_quoted_content,
    ACTIONS(27), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(13), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [129] = 4,
    ACTIONS(33), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(37), 1,
      sym_single_quoted_content,
    ACTIONS(35), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(10), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [144] = 4,
    ACTIONS(41), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(43), 1,
      sym_backticked_content,
    ACTIONS(39), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(5), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [159] = 4,
    ACTIONS(45), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(50), 1,
      sym_single_quoted_content,
    ACTIONS(47), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(10), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [174] = 4,
    ACTIONS(53), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(57), 1,
      sym_single_quoted_content,
    ACTIONS(55), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(8), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [189] = 4,
    ACTIONS(61), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(63), 1,
      sym_double_quoted_content,
    ACTIONS(59), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(7), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [204] = 4,
    ACTIONS(68), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(70), 1,
      sym_double_quoted_content,
    ACTIONS(65), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(13), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [219] = 1,
    ACTIONS(73), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [226] = 2,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 3,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [235] = 1,
    ACTIONS(79), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [242] = 1,
    ACTIONS(81), 4,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [249] = 1,
    ACTIONS(83), 3,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [255] = 1,
    ACTIONS(85), 3,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [261] = 1,
    ACTIONS(87), 3,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [267] = 1,
    ACTIONS(89), 3,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [273] = 1,
    ACTIONS(91), 3,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [279] = 1,
    ACTIONS(93), 3,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [285] = 2,
    ACTIONS(95), 1,
      anon_sym_COLON_DASH,
    ACTIONS(97), 1,
      anon_sym_DOT,
  [292] = 1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [296] = 1,
    ACTIONS(101), 1,
      anon_sym_DOT,
  [300] = 1,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
  [304] = 1,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
  [308] = 1,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
  [312] = 1,
    ACTIONS(109), 1,
      anon_sym_DOT,
  [316] = 1,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
  [320] = 1,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 99,
  [SMALL_STATE(7)] = 114,
  [SMALL_STATE(8)] = 129,
  [SMALL_STATE(9)] = 144,
  [SMALL_STATE(10)] = 159,
  [SMALL_STATE(11)] = 174,
  [SMALL_STATE(12)] = 189,
  [SMALL_STATE(13)] = 204,
  [SMALL_STATE(14)] = 219,
  [SMALL_STATE(15)] = 226,
  [SMALL_STATE(16)] = 235,
  [SMALL_STATE(17)] = 242,
  [SMALL_STATE(18)] = 249,
  [SMALL_STATE(19)] = 255,
  [SMALL_STATE(20)] = 261,
  [SMALL_STATE(21)] = 267,
  [SMALL_STATE(22)] = 273,
  [SMALL_STATE(23)] = 279,
  [SMALL_STATE(24)] = 285,
  [SMALL_STATE(25)] = 292,
  [SMALL_STATE(26)] = 296,
  [SMALL_STATE(27)] = 300,
  [SMALL_STATE(28)] = 304,
  [SMALL_STATE(29)] = 308,
  [SMALL_STATE(30)] = 312,
  [SMALL_STATE(31)] = 316,
  [SMALL_STATE(32)] = 320,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [16] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_string, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_string, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_term, 4, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [103] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_swiprolog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "swiprolog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
