/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 51
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON_DASH = 1,
  anon_sym_DOT = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  sym_unquoted_atom = 6,
  aux_sym_quoted_atom_token1 = 7,
  sym_format_string_placeholder = 8,
  sym_single_quoted_character_escape = 9,
  sym_single_quoted_content = 10,
  aux_sym_double_quoted_string_token1 = 11,
  sym_double_quoted_character_escape = 12,
  sym_double_quoted_content = 13,
  aux_sym_backtick_string_token1 = 14,
  sym_backticked_character_escape = 15,
  sym_backticked_content = 16,
  sym_variable = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_PIPE = 20,
  sym_source_file = 21,
  sym_directive = 22,
  sym_clause = 23,
  sym__term = 24,
  sym__restricted_operators_term = 25,
  sym_compound_term = 26,
  sym_atom = 27,
  sym_quoted_atom = 28,
  sym__single_quoted_inner = 29,
  sym_string = 30,
  sym_double_quoted_string = 31,
  sym__double_quoted_string_inner = 32,
  sym_backtick_string = 33,
  sym__backtick_string_inner = 34,
  sym_list_literal = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_compound_term_repeat1 = 37,
  aux_sym_quoted_atom_repeat1 = 38,
  aux_sym_double_quoted_string_repeat1 = 39,
  aux_sym_backtick_string_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_DASH] = ":-",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_unquoted_atom] = "unquoted_atom",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [sym_format_string_placeholder] = "format_string_placeholder",
  [sym_single_quoted_character_escape] = "single_quoted_character_escape",
  [sym_single_quoted_content] = "single_quoted_content",
  [aux_sym_double_quoted_string_token1] = "double_quoted_string_token1",
  [sym_double_quoted_character_escape] = "double_quoted_character_escape",
  [sym_double_quoted_content] = "double_quoted_content",
  [aux_sym_backtick_string_token1] = "backtick_string_token1",
  [sym_backticked_character_escape] = "backticked_character_escape",
  [sym_backticked_content] = "backticked_content",
  [sym_variable] = "variable",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PIPE] = "|",
  [sym_source_file] = "source_file",
  [sym_directive] = "directive",
  [sym_clause] = "clause",
  [sym__term] = "_term",
  [sym__restricted_operators_term] = "_restricted_operators_term",
  [sym_compound_term] = "compound_term",
  [sym_atom] = "atom",
  [sym_quoted_atom] = "quoted_atom",
  [sym__single_quoted_inner] = "_single_quoted_inner",
  [sym_string] = "string",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym__double_quoted_string_inner] = "_double_quoted_string_inner",
  [sym_backtick_string] = "backtick_string",
  [sym__backtick_string_inner] = "_backtick_string_inner",
  [sym_list_literal] = "list_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_compound_term_repeat1] = "compound_term_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [aux_sym_double_quoted_string_repeat1] = "double_quoted_string_repeat1",
  [aux_sym_backtick_string_repeat1] = "backtick_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_unquoted_atom] = sym_unquoted_atom,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [sym_format_string_placeholder] = sym_format_string_placeholder,
  [sym_single_quoted_character_escape] = sym_single_quoted_character_escape,
  [sym_single_quoted_content] = sym_single_quoted_content,
  [aux_sym_double_quoted_string_token1] = aux_sym_double_quoted_string_token1,
  [sym_double_quoted_character_escape] = sym_double_quoted_character_escape,
  [sym_double_quoted_content] = sym_double_quoted_content,
  [aux_sym_backtick_string_token1] = aux_sym_backtick_string_token1,
  [sym_backticked_character_escape] = sym_backticked_character_escape,
  [sym_backticked_content] = sym_backticked_content,
  [sym_variable] = sym_variable,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_source_file] = sym_source_file,
  [sym_directive] = sym_directive,
  [sym_clause] = sym_clause,
  [sym__term] = sym__term,
  [sym__restricted_operators_term] = sym__restricted_operators_term,
  [sym_compound_term] = sym_compound_term,
  [sym_atom] = sym_atom,
  [sym_quoted_atom] = sym_quoted_atom,
  [sym__single_quoted_inner] = sym__single_quoted_inner,
  [sym_string] = sym_string,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym__double_quoted_string_inner] = sym__double_quoted_string_inner,
  [sym_backtick_string] = sym_backtick_string,
  [sym__backtick_string_inner] = sym__backtick_string_inner,
  [sym_list_literal] = sym_list_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_compound_term_repeat1] = aux_sym_compound_term_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [aux_sym_double_quoted_string_repeat1] = aux_sym_double_quoted_string_repeat1,
  [aux_sym_backtick_string_repeat1] = aux_sym_backtick_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_unquoted_atom] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_format_string_placeholder] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_double_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_double_quoted_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_backtick_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_backticked_character_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_backticked_content] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym__restricted_operators_term] = {
    .visible = false,
    .named = true,
  },
  [sym_compound_term] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quoted_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym__double_quoted_string_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_backtick_string] = {
    .visible = true,
    .named = true,
  },
  [sym__backtick_string_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_list_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_backtick_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_functor = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_functor] = "functor",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_functor, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 22,
        '\'', 17,
        '(', 13,
        ')', 15,
        ',', 14,
        '.', 12,
        ':', 4,
        '[', 31,
        '\\', 2,
        ']', 32,
        '`', 26,
        '|', 33,
        '~', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 23,
        '\'', 19,
        '`', 27,
        '\\', 19,
        'n', 19,
        'r', 19,
        't', 19,
        'v', 19,
      );
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == '`') ADVANCE(26);
      if (lookahead == '~') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == 'n' ||
          lookahead == 't' ||
          lookahead == '~') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == '\\' ||
          lookahead == '`' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(27);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_unquoted_atom);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_format_string_placeholder);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_single_quoted_character_escape);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_double_quoted_string_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_double_quoted_character_escape);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '~') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_backtick_string_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_backticked_character_escape);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_backticked_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_backticked_content);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_unquoted_atom] = ACTIONS(1),
    [aux_sym_quoted_atom_token1] = ACTIONS(1),
    [sym_format_string_placeholder] = ACTIONS(1),
    [sym_single_quoted_character_escape] = ACTIONS(1),
    [aux_sym_double_quoted_string_token1] = ACTIONS(1),
    [sym_double_quoted_character_escape] = ACTIONS(1),
    [aux_sym_backtick_string_token1] = ACTIONS(1),
    [sym_backticked_character_escape] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(46),
    [sym_directive] = STATE(2),
    [sym_clause] = STATE(2),
    [sym__term] = STATE(45),
    [sym__restricted_operators_term] = STATE(45),
    [sym_compound_term] = STATE(45),
    [sym_atom] = STATE(14),
    [sym_quoted_atom] = STATE(16),
    [sym_string] = STATE(45),
    [sym_double_quoted_string] = STATE(22),
    [sym_backtick_string] = STATE(22),
    [sym_list_literal] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_COLON_DASH] = ACTIONS(5),
    [sym_unquoted_atom] = ACTIONS(7),
    [aux_sym_quoted_atom_token1] = ACTIONS(9),
    [aux_sym_double_quoted_string_token1] = ACTIONS(11),
    [aux_sym_backtick_string_token1] = ACTIONS(13),
    [sym_variable] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(5), 1,
      anon_sym_COLON_DASH,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(15), 1,
      sym_variable,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(3), 3,
      sym_directive,
      sym_clause,
      aux_sym_source_file_repeat1,
    STATE(45), 5,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [47] = 13,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_COLON_DASH,
    ACTIONS(26), 1,
      sym_unquoted_atom,
    ACTIONS(29), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(32), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(35), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(38), 1,
      sym_variable,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(3), 3,
      sym_directive,
      sym_clause,
      aux_sym_source_file_repeat1,
    STATE(45), 5,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [94] = 10,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      sym_variable,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(50), 5,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [130] = 10,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(46), 1,
      sym_variable,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(49), 5,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [166] = 11,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(48), 1,
      sym_variable,
    ACTIONS(50), 1,
      anon_sym_RBRACK,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(40), 4,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [204] = 10,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      sym_variable,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(47), 5,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [240] = 10,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(54), 1,
      sym_variable,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(48), 5,
      sym__term,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [276] = 10,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      sym_variable,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(42), 4,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [311] = 10,
    ACTIONS(7), 1,
      sym_unquoted_atom,
    ACTIONS(9), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(11), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(13), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      sym_variable,
    STATE(14), 1,
      sym_atom,
    STATE(16), 1,
      sym_quoted_atom,
    STATE(22), 2,
      sym_double_quoted_string,
      sym_backtick_string,
    STATE(44), 4,
      sym__restricted_operators_term,
      sym_compound_term,
      sym_string,
      sym_list_literal,
  [346] = 1,
    ACTIONS(60), 8,
      ts_builtin_sym_end,
      anon_sym_COLON_DASH,
      sym_unquoted_atom,
      aux_sym_quoted_atom_token1,
      aux_sym_double_quoted_string_token1,
      aux_sym_backtick_string_token1,
      sym_variable,
      anon_sym_LBRACK,
  [357] = 1,
    ACTIONS(62), 8,
      ts_builtin_sym_end,
      anon_sym_COLON_DASH,
      sym_unquoted_atom,
      aux_sym_quoted_atom_token1,
      aux_sym_double_quoted_string_token1,
      aux_sym_backtick_string_token1,
      sym_variable,
      anon_sym_LBRACK,
  [368] = 1,
    ACTIONS(64), 8,
      ts_builtin_sym_end,
      anon_sym_COLON_DASH,
      sym_unquoted_atom,
      aux_sym_quoted_atom_token1,
      aux_sym_double_quoted_string_token1,
      aux_sym_backtick_string_token1,
      sym_variable,
      anon_sym_LBRACK,
  [379] = 2,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [391] = 1,
    ACTIONS(70), 7,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [401] = 1,
    ACTIONS(72), 7,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [411] = 1,
    ACTIONS(74), 7,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [421] = 4,
    ACTIONS(78), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(80), 1,
      sym_double_quoted_content,
    ACTIONS(76), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(29), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [436] = 4,
    ACTIONS(84), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(86), 1,
      sym_backticked_content,
    ACTIONS(82), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(33), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [451] = 1,
    ACTIONS(88), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [460] = 4,
    ACTIONS(90), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(95), 1,
      sym_single_quoted_content,
    ACTIONS(92), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(21), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [475] = 1,
    ACTIONS(98), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [484] = 1,
    ACTIONS(100), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [493] = 4,
    ACTIONS(105), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(107), 1,
      sym_double_quoted_content,
    ACTIONS(102), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(24), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [508] = 1,
    ACTIONS(110), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [517] = 4,
    ACTIONS(112), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(116), 1,
      sym_single_quoted_content,
    ACTIONS(114), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(21), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [532] = 1,
    ACTIONS(118), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [541] = 4,
    ACTIONS(123), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(125), 1,
      sym_backticked_content,
    ACTIONS(120), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(28), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [556] = 4,
    ACTIONS(130), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(132), 1,
      sym_double_quoted_content,
    ACTIONS(128), 2,
      sym_format_string_placeholder,
      sym_double_quoted_character_escape,
    STATE(24), 2,
      sym__double_quoted_string_inner,
      aux_sym_double_quoted_string_repeat1,
  [571] = 1,
    ACTIONS(134), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [580] = 1,
    ACTIONS(136), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [589] = 1,
    ACTIONS(138), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [598] = 4,
    ACTIONS(142), 1,
      aux_sym_backtick_string_token1,
    ACTIONS(144), 1,
      sym_backticked_content,
    ACTIONS(140), 2,
      sym_format_string_placeholder,
      sym_backticked_character_escape,
    STATE(28), 2,
      sym__backtick_string_inner,
      aux_sym_backtick_string_repeat1,
  [613] = 4,
    ACTIONS(146), 1,
      aux_sym_quoted_atom_token1,
    ACTIONS(150), 1,
      sym_single_quoted_content,
    ACTIONS(148), 2,
      sym_format_string_placeholder,
      sym_single_quoted_character_escape,
    STATE(26), 2,
      sym__single_quoted_inner,
      aux_sym_quoted_atom_repeat1,
  [628] = 1,
    ACTIONS(152), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [637] = 1,
    ACTIONS(154), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [646] = 1,
    ACTIONS(156), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [655] = 1,
    ACTIONS(158), 6,
      anon_sym_COLON_DASH,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [664] = 3,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_compound_term_repeat1,
    ACTIONS(163), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [676] = 4,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 1,
      anon_sym_PIPE,
    STATE(41), 1,
      aux_sym_compound_term_repeat1,
  [689] = 4,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
    ACTIONS(173), 1,
      anon_sym_PIPE,
    STATE(39), 1,
      aux_sym_compound_term_repeat1,
  [702] = 1,
    ACTIONS(163), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [709] = 3,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_compound_term_repeat1,
  [719] = 3,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_compound_term_repeat1,
  [729] = 2,
    ACTIONS(179), 1,
      anon_sym_COLON_DASH,
    ACTIONS(181), 1,
      anon_sym_DOT,
  [736] = 1,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
  [740] = 1,
    ACTIONS(185), 1,
      anon_sym_DOT,
  [744] = 1,
    ACTIONS(187), 1,
      anon_sym_DOT,
  [748] = 1,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
  [752] = 1,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 130,
  [SMALL_STATE(6)] = 166,
  [SMALL_STATE(7)] = 204,
  [SMALL_STATE(8)] = 240,
  [SMALL_STATE(9)] = 276,
  [SMALL_STATE(10)] = 311,
  [SMALL_STATE(11)] = 346,
  [SMALL_STATE(12)] = 357,
  [SMALL_STATE(13)] = 368,
  [SMALL_STATE(14)] = 379,
  [SMALL_STATE(15)] = 391,
  [SMALL_STATE(16)] = 401,
  [SMALL_STATE(17)] = 411,
  [SMALL_STATE(18)] = 421,
  [SMALL_STATE(19)] = 436,
  [SMALL_STATE(20)] = 451,
  [SMALL_STATE(21)] = 460,
  [SMALL_STATE(22)] = 475,
  [SMALL_STATE(23)] = 484,
  [SMALL_STATE(24)] = 493,
  [SMALL_STATE(25)] = 508,
  [SMALL_STATE(26)] = 517,
  [SMALL_STATE(27)] = 532,
  [SMALL_STATE(28)] = 541,
  [SMALL_STATE(29)] = 556,
  [SMALL_STATE(30)] = 571,
  [SMALL_STATE(31)] = 580,
  [SMALL_STATE(32)] = 589,
  [SMALL_STATE(33)] = 598,
  [SMALL_STATE(34)] = 613,
  [SMALL_STATE(35)] = 628,
  [SMALL_STATE(36)] = 637,
  [SMALL_STATE(37)] = 646,
  [SMALL_STATE(38)] = 655,
  [SMALL_STATE(39)] = 664,
  [SMALL_STATE(40)] = 676,
  [SMALL_STATE(41)] = 689,
  [SMALL_STATE(42)] = 702,
  [SMALL_STATE(43)] = 709,
  [SMALL_STATE(44)] = 719,
  [SMALL_STATE(45)] = 729,
  [SMALL_STATE(46)] = 736,
  [SMALL_STATE(47)] = 740,
  [SMALL_STATE(48)] = 744,
  [SMALL_STATE(49)] = 748,
  [SMALL_STATE(50)] = 752,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 4, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__restricted_operators_term, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_literal, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_atom_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_string, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 3, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_backtick_string_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_literal, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_string, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_term, 4, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_literal, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_literal, 5, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_term, 5, 0, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_literal, 6, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_term_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_term_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [183] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_swiprolog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "swiprolog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
